all: exo1 exo2 exo3 exo4 exo5

exo1: exo1.cpp
	g++ -o exo1 exo1.cpp -Wextra -Wall -pedantic

exo2: exo2.cpp
	g++ -o exo2 exo2.cpp -Wextra -Wall -pedantic

exo3: exo3.cpp
	g++ -o exo3 exo3.cpp -Wextra -Wall -pedantic

exo4: exo4.cpp
	g++ -o exo4 exo4.cpp -Wextra -Wall -pedantic	

exo5: exo5.cpp
	g++ -o exo5 exo5.cpp -Wextra -Wall -pedantic